name = "kit_builder"
description = "Builder for kit"
version = "0.1.0-dev"
licenses= "GPL-3.0-or-later"

authors = ["Fraser Wilson"]
maintainers = ["Fraser Wilson <fraser@thewhitelion.eu>"]
maintainers-logins = ["blancolioni"]

tags = ["utility", "database", "compiler"]
website = "https://github.com/blancolioni/kit_builder"

executables = ["kit_builder"]
[[depends-on]]
wl_lib = "~0.1.0-dev"
[[depends-on]]
parse_args = "~0.9.0"
[[depends-on]]
kit_base = "~0.1.0-dev"
[[depends-on]]
kit_schema = "~0.1.0-dev"
[[depends-on]]
kit_parser = "~0.1.0-dev"
[[depends-on]]
kit_generator = "~0.1.0-dev"
